In [1]:
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
df = pd.read_csv("car data.csv")

In [3]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [7]:
df.tail()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
296,city,2016,9.50,11.6,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.9,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.0,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.5,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.9,5464,Petrol,Dealer,Manual,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [5]:
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [6]:
numerical_features = [feature for feature in df.columns if df[feature].dtype != 'O']
categorical_features = [feature for feature in df.columns if df[feature].dtype == 'O']

print(f"Numerical Features are {len(numerical_features)}: {numerical_features}")
print(f"Categorical Features are {len(categorical_features)}: {categorical_features}")

Numerical Features are 5: ['Year', 'Selling_Price', 'Present_Price', 'Kms_Driven', 'Owner']
Categorical Features are 4: ['Car_Name', 'Fuel_Type', 'Seller_Type', 'Transmission']

In [9]:
df['Owner'].value_counts()

Owner
0    290
1     10
3      1
Name: count, dtype: int64

#### Owner can also be a categorical feature as we can see

In [10]:
categorical_features.append('Owner')
numerical_features.remove('Owner')

print(f"Numerical Features are {len(numerical_features)}: {numerical_features}")
print(f"Categorical Features are {len(categorical_features)}: {categorical_features}")

Numerical Features are 4: ['Year', 'Selling_Price', 'Present_Price', 'Kms_Driven']
Categorical Features are 5: ['Car_Name', 'Fuel_Type', 'Seller_Type', 'Transmission', 'Owner']

In [11]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [16]:
df_encoded = pd.get_dummies(
    df,
    columns=categorical_features,
    drop_first=True 
)

In [17]:
df_encoded

,Year,Selling_Price,Present_Price,Kms_Driven,Car_Name_Activa 3g,Car_Name_Activa 4g,Car_Name_Bajaj ct 100,Car_Name_Bajaj Avenger 150,Car_Name_Bajaj Avenger 150 street,Car_Name_Bajaj Avenger 220,...,Car_Name_verna,Car_Name_vitara brezza,Car_Name_wagon r,Car_Name_xcent,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual,Owner_1,Owner_3
0,2014,3.35,5.59,27000,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,False,False
1,2013,4.75,9.54,43000,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
2,2017,7.25,9.85,6900,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,False,False
3,2011,2.85,4.15,5200,False,False,False,False,False,False,...,False,False,True,False,False,True,False,True,False,False
4,2014,4.60,6.87,42450,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
297,2015,4.00,5.90,60000,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,False,False
298,2009,3.35,11.00,87934,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,False,False
299,2017,11.50,12.50,9000,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
300,2016,5.30,5.90,5464,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,False,False

In [18]:
X=df_encoded.drop('Selling_Price', axis=1)
y=df_encoded['Selling_Price']

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler

### Linear Regression

In [27]:
lr = LinearRegression()

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lr.fit(X_train_scaled, y_train)
y_pred_lr = lr.predict(X_test_scaled)
print("Scaled Linear Regression R²:", r2_score(y_test, y_pred_lr))

Scaled Linear Regression R²: 0.599503818404751

### Random Forest Regressor

In [30]:
rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest R²:", r2_rf)

Random Forest R²: 0.96410359427943

so as we can see Random Forest has good accuracy

In [34]:
import joblib
import os

# create folder
os.makedirs("../models", exist_ok=True)

# save model
joblib.dump(rf, "../models/random_forest_model.pkl")

['../models/random_forest_model.pkl']

In [35]:
X_train.columns

Index(['Year', 'Present_Price', 'Kms_Driven', 'Car_Name_Activa 3g',
       'Car_Name_Activa 4g', 'Car_Name_Bajaj  ct 100',
       'Car_Name_Bajaj Avenger 150', 'Car_Name_Bajaj Avenger 150 street',
       'Car_Name_Bajaj Avenger 220', 'Car_Name_Bajaj Avenger 220 dtsi',
       ...
       'Car_Name_verna', 'Car_Name_vitara brezza', 'Car_Name_wagon r',
       'Car_Name_xcent', 'Fuel_Type_Diesel', 'Fuel_Type_Petrol',
       'Seller_Type_Individual', 'Transmission_Manual', 'Owner_1', 'Owner_3'],
      dtype='object', length=106)

In [36]:
joblib.dump(list(X_train.columns), "../models/feature_columns.pkl")

['../models/feature_columns.pkl']